# TODO
# Figure out nvm usage
# Learn vi mode for CLI editing
# Figure out reloading of nu config

# color, abbreviation
# green  g
# red    r
# blue   u
# black  b
# yellow y
# purple p
# cyan   c
# white  w
# attribute, abbreviation
# bold       b
# underline  u

# italic     i
# dimmed     d
# reverse    r
# abbreviated: green bold = gb, red underline = ru, blue dimmed = ud
# or verbose: green_bold, red_underline, blue_dimmed

startup = ["source ~/.config/nu/startup.nu"]

ctrlc_exit = false
complete_from_path = true
pivot_mode = "auto"
prompt = "build-string (ansi w) (do -i { if ($nu.env | select TMUX | empty?) { date now | date format -t '[%H:%M] ' } {} }) (ansi u) (pwd) (ansi y) (do -i { git rev-parse --abbrev-ref HEAD } | str trim | str find-replace '(.*)' ' ($1)') (ansi reset) ' > '"
rm_always_trash = true
skip_welcome_message = true
table_mode = "compact_double"
table_pager = "less"

path = [
  "/Users/lukepetherbridge/bin",
  "/Users/lukepetherbridge/.nvm/versions/node/v14.16.1/bin",
  "/Users/lukepetherbridge/.fzf/bin",
  "/Users/lukepetherbridge/.cargo/bin",
  "/Users/LucasPetherbridge/bin",
  "/Users/LucasPetherbridge/.nvm/versions/node/v14.16.1/bin",
  "/Users/LucasPetherbridge/.fzf/bin",
  "/Users/LucasPetherbridge/.cargo/bin",
  "/usr/local/opt/openjdk/bin",
  "/bin",
  "/usr/local/bin",
  "/usr/bin",
  "/usr/sbin",
  "/sbin",
]

[env]
EDITOR = "nvim"
FZF_DEFAULT_OPTS = "--height 50% --layout=reverse --border --inline-info"
FZF_CTRL_T_COMMAND = "rg --files --hidden --no-ignore --ignore-file ~/.rgignore"
FZF_DEFAULT_COMMAND = "rg --files --hidden --no-ignore --ignore-file ~/.rgignore"
GOPATH = "/Users/lukepetherbridge/dev:/Users/LucasPetherbridge/dev"
GOROOT = ""
JAVA_HOME = "/usr/local/opt/openjdk/"
LESS = "-RFX"
PAGER = "nvim -nR -i NONE -c 'setlocal ft=man nofoldenable nolist'"
MANPAGER = "nvim -nR -i NONE -c 'setlocal ft=man nofoldenable nolist'"
SPRING_PROFILES_ACTIVE = "local"

[color_config]
header_align = "l" # left|l, right|r, center|c
header_bold = true
header_color = "c" # green|g, red|r, blue|u, black|b, yellow|y, purple|p, cyan|c, white|w
index_color = "rd"
leading_trailing_space_bg = "white"
primitive_binary = "cyan"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "white"
primitive_decimal = "red"
primitive_duration = "blue"
primitive_filesize = "ub"
primitive_int = "green"
primitive_line = "yellow"
primitive_path = "yellow"
primitive_pattern = "white"
primitive_range = "purple"
primitive_string = "pb"
separator_color = "purple"

[line_editor]
auto_add_history = true
bell_style = "visible" # audible, none, visible
color_mode = "enabled" # enabled, forced, disabled
completion_match_method = "case-insensitive" # case-insensitive, case-sensitive
edit_mode = "vi"
history_duplicates = "ignoreconsecutive" # alwaysadd, ignoreconsecutive
history_ignore_space = "true"
max_history_size = 100000
tab_stop = 4

[textview]
colored_output = true
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen" # Always, QuitIfOneScreen, Never
tab_width = 4
true_color = true
use_italics = true
wrapping_mode = "Character" # Character, NoWrapping
