#
#                                    i  t
#                                   LE  ED.
#                                  L#E  E#K:
#                                 G#W.  E##W;
#                                D#K.   E#E##t
#                               E#K.    E#ti##f
#                             .E#E.     E#t ;##D.
#                            .K#E       E#ELLE##K:
#                           .K#D        E#L;;;;;;,
#                          .W#G         E#t
#                         :W##########WtE#t
#                         :,,,,,,,,,,,,,.
#
#
#     Personal nushell configuration of Luke Petherbridge <me@lukeworks.tech>



# =============================================================================
# Config   {{{1
# =============================================================================

startup = [
  "mkdir ~/.cache/starship",
  "if (ls ~/.cache/starship/ | where name =~ init | length) == 0 { starship init nu | save ~/.cache/starship/init.nu } {}",
  "source ~/.config/nu/startup.nu",
]

ctrlc_exit = false
complete_from_path = true
pivot_mode = "auto"
prompt = "starship prompt"
rm_always_trash = true
skip_welcome_message = true
table_mode = "compact_double"
table_pager = "less"

path = [
  "/usr/local/bin",
  "/usr/games/",
  "/usr/bin",
  "/bin",
  "/usr/sbin",
  "/sbin",
]


# =============================================================================
# Environment   {{{1
# =============================================================================

[env]
EDITOR = "nvim"
FZF_DEFAULT_OPTS = "--height 50% --layout=reverse --border --inline-info"
FZF_CTRL_T_COMMAND = "rg --files --hidden"
FZF_DEFAULT_COMMAND = "rg --files --hidden"
LESS = "-RFX"
PAGER = "nvim +Man!"
MANPAGER = "nvim +Man!"
JAVA_HOME = "/usr/local/opt/openjdk@11"


# =============================================================================
# Colors   {{{1
# =============================================================================

[color_config]
header_align = "l" # left|l, right|r, center|c
header_bold = true
header_color = "c" # green|g, red|r, blue|u, black|b, yellow|y, purple|p, cyan|c, white|w
index_color = "rd"
leading_trailing_space_bg = "white"
primitive_binary = "cyan"
primitive_boolean = "green"
primitive_columnpath = "cyan"
primitive_date = "white"
primitive_decimal = "red"
primitive_duration = "blue"
primitive_filesize = "ub"
primitive_int = "green"
primitive_line = "yellow"
primitive_path = "yellow"
primitive_pattern = "white"
primitive_range = "purple"
primitive_string = "pb"
separator_color = "purple"


# =============================================================================
# Editor   {{{1
# =============================================================================

[line_editor]
auto_add_history = true
bell_style = "visible" # audible, none, visible
color_mode = "enabled" # enabled, forced, disabled
completion_type = "list" # circular, list
completion_match_method = "case-sensitive" # case-insensitive, case-sensitive
edit_mode = "vi"
history_duplicates = "ignoreconsecutive" # alwaysadd, ignoreconsecutive
history_ignore_space = true
max_history_size = 100000
tab_stop = 4


# =============================================================================
# Text   {{{1
# =============================================================================

[textview]
colored_output = true
header = true
line_numbers = true
pager = "less"
paging_mode = "QuitIfOneScreen" # Always, QuitIfOneScreen, Never
tab_width = 4
true_color = true
use_italics = true
wrapping_mode = "Character" # Character, NoWrapping

# =============================================================================
# Reference   {{{1
# =============================================================================

# color, abbreviation
# green  g
# red    r
# blue   u
# black  b
# yellow y
# purple p
# cyan   c
# white  w
# attribute, abbreviation
# bold       b
# underline  u

# italic     i
# dimmed     d
# reverse    r
# abbreviated: green bold = gb, red underline = ru, blue dimmed = ud
# or verbose: green_bold, red_underline, blue_dimmed


# vim: foldmethod=marker foldlevel=0
