#
#                                    i  t
#                                   LE  ED.
#                                  L#E  E#K:
#                                 G#W.  E##W;
#                                D#K.   E#E##t
#                               E#K.    E#t ##f
#                             .E#E.     E#t  ;#D.
#                            .K#E       E#ELLE##K:
#                           .K#D        E#L;;;;;;,
#                          .W#G      .K E#t
#                         :W##########W E#t
#                         :,,,,,,,,,,,, .
#
#
#     Personal starship configuration of Luke Petherbridge <me@lukeworks.tech>

# env STARSHIP_LOG=trace starship timings
command_timeout = 5000

format = """
$python\
$directory\
${custom.disk}\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#86BBD8)\
$c\
$golang\
$java\
$lua\
$nodejs\
$rust\
$zig\
[](fg:#86BBD8 bg:#33658A)\
$time\
[](fg:#33658A)\
\n$character
"""

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"
read_only = "  "

[custom.disk]
command = "df -h / | awk 'NR==2{print $4}'"
when = true
symbol = " "
style = "bg:#434C5E fg:#CCCCCC"
format = "[\\[$symbol$output\\]]($style)"

[git_branch]
symbol = " "
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind]($style)'
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked = "? "
modified = " "
stashed = ""
staged = ""
renamed = ""
deleted = ""

[character]
success_symbol = "[❯](bold fg:#06969A)"
error_symbol = "[❯](bold red)"

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

[battery]
charging_symbol = "⚡️ "

[[battery.display]]
threshold = 15
style = "bold red"
discharging_symbol = "🔋 "

[[battery.display]]
threshold = 30
style = "bold yellow"

[c]
symbol = " "
style = "bg:#86BBD8 fg:#1d2021"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8 fg:#1d2021"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:#86BBD8 fg:#1d2021"
format = '[ $symbol ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#1d2021"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#86BBD8 fg:#1d2021"
format = '[ $symbol \($virtualenv\) ]($style)[](bg:#434C5E fg:#86BBD8)'

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#1d2021"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = " "
style = "bg:#86BBD8 fg:#1d2021"
format = '[ $symbol $(version) ]($style)'
