# Omarchy should be setting these but isn't for some reason
env = OMARCHY_PATH,$HOME/.local/share/omarchy

# NVIDIA environment variables
# See: https://wiki.hypr.land/Nvidia/
env = NVD_BACKEND,"direct" # Requires libva-nvidia-driver installed
env = LIBVA_DRIVER_NAME,"nvidia"
env = __GLX_VENDOR_LIBRARY_NAME,"nvidia"
# Helps resume from sleep
env = OGL_DEDICATED_HW_STATE_PER_CONTEXT,"ENABLE_ROBUST"
env = ELECTRON_OZONE_PLATFORM_HINT,"auto"
