# TetaNES
windowrule = float on, match:title (TetaNES.*)
windowrule = center on, match:title (TetaNES.*)

# POL
windowrule = float on, match:title (PlayOnline.*)
windowrule = center on, match:title (PlayOnline.*)

# FF
windowrule = fullscreen on, match:title (Final Fantasy.*)

# clipse clipboard manager
windowrule = float on, match:class (clipse)
windowrule = center on, match:title (PlayOnline.*)
windowrule = stay_focused on, match:class (clipse)

# Steam
windowrule = size monitor_w*0.8 monitor_h*0.9, match:class steam
