---
bar:
  height: 26
  location: top
  spacing: 15
  margin: 7
  font: DejaVuSansM Nerd Font Mono:pixelsize=16
  foreground: bbbbbbff # #bbbbbb
  background: 222222ff # #222222
  border:
    width: 0
    color: 444444ff # #444444
    margin: 0
    top-margin: 0
  left:
    - dwl:
        number-of-tags: 4
        anchors:
          - occupied: &occupied { foreground: 66bbffff } # #66bbff
          - focused: &focused { foreground: ff8800ff } # # #ff8800
          - urgent: &urgent { foreground: 990000ff } # #990000
          - default: &default { foreground: ccccccff } # #cccccc
        dwl-info-filename: "/tmp/dwltags"
        name-of-tags: ["", "󰍪", "", "󰍹"]
        content:
          list:
            items:
              - map:
                  margin: 8
                  font: DejaVuSansM Nerd Font Mono:pixelsize=20
                  conditions:
                    # default tag
                    id == 0:
                      {
                        string:
                          {
                            text: "{layout}",
                            font: DejaVuSansM Nerd Font Mono:pixelsize=16,
                          },
                      }
                    urgent: { string: { text: "{name}", <<: *urgent } }
                    ~empty:
                      map:
                        conditions:
                          selected: { string: { text: "{name}", <<: *focused } }
                          ~selected:
                            { string: { text: "{name}", <<: *occupied } }
                    empty:
                      map:
                        conditions:
                          selected: { string: { text: "{name}", <<: *focused } }
                          ~selected:
                            { string: { text: "{name}", <<: *default } }
              - map:
                  margin: 20
                  conditions:
                    # default tag
                    id == 0: { string: { text: "{title}" } }
  right:
    # TODO: load averages instead?
    - cpu:
        content:
          map:
            conditions:
              id < 0: { string: { text: "CPU: {cpu:3}%" } }
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {
                  string: { text: "󰝟 {cubic_volume}%", foreground: ff0000ff },
                } # #ff0000
              ~muted: { string: { text: " {cubic_volume}%" } }
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        <<: *volume
    # TODO: battery
    - clock:
        time-format: "%H:%M"
        date-format: "%Y-%m-%d"
        content:
          - string: { text: "{date}", margin: 10 }
          - string: { text: "{time}" }
